security:
  jwt-secret: your-256-bit-secret-key
  jwt-expiration: 86400000
  allowed-origins:
    - http://localhost:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  public-paths:
    - /auth/**
    - /public/**